name = "ZFSL"
author = "felowek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "decbc62b7e47c432008bc84d1ce9fd45605d919879b37ba545f46e121f00ead4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
