name = "ZFSL"
author = "felowek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96a531ad943b177894ca86295521745ae4b0f38ac2fa73772287efb0010efbee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
