name = "ZFSL"
author = "felowek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3925e1aaa05a3f58bfdaddfd1468e30930e81f94c225bfad918790170cc54c45"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.236"
