#=========[ Pillager Caravans Common Config ]========
# Please prefer editing the config through the in-game 
# configuration screen (available via the mods list),
# as it includes many hints and quality-of-life improvements.
#====================================================
enablePillagerCaravans = true
enableEncounterToast = true
toastLightMode = false
# Default: 24000
# Range: > 0
worldAgeRequired = 18000
# Default: 1200
# Range: > 0
spawnAttemptCooldown = 1000
# Default: 1.0
# Range: 0.1 ~ 10.0
spawnCooldownMultiplier = 1.0
# Default: 9
# Range: 0 ~ 100
smallCaravanSpawnWeight = 10
# Default: 48000
# Range: > 12000
smallCaravanSpawnCooldown = 24000
# Default: 12000
# Range: > 12000
smallCaravanDespawnDelay = 12000
# Default: 3
# Range: 0 ~ 100
mediumCaravanSpawnWeight = 5
# Default: 96000
# Range: > 12000
mediumCaravanSpawnCooldown = 48000
# Default: 24000
# Range: > 12000
mediumCaravanDespawnDelay = 24000
# Default: 1
# Range: 0 ~ 100
largeCaravanSpawnWeight = 2
# Default: 144000
# Range: > 12000
largeCaravanSpawnCooldown = 72000
# Default: 36000
# Range: > 12000
largeCaravanDespawnDelay = 36000
# Default: 32
# Range: > 0
spawnDistance = 24
# Default: 32
# Range: > 0
spawnDistanceVariance = 32
# Default: 4
# Range: 0 ~ 15
maxBlockLight = 4
# Default: 3
# Range: 0 ~ 64
villageSafeZone = 3
allowFollowerTeleport = true
allowLeashedTeleport = true
