#Truly Dark properties file
#Wed Jul 29 22:33:53 CEST 2026
biome_blacklist=alexscaves\:primordial_caves,alexscaves\:candy_cavity
cloud_darkness=0.15000000000000002
dark_default=true
dark_end=true
dark_end_fog=0.2
dark_moon=true
dark_nether=true
dark_nether_fog=0.7
dark_overworld=true
dark_sky=true
dark_skyless=true
entity_light_floor=0.15000000000000002
fog_darkness=0.25
hard_lock=false
ignore_moon_phase=false
moon_phase_intensity=0.6000000000000001
only_affect_block_light=false
pack_configured=true
require_client_mod=true
setup_version=Manual
sky_darkness=0.4
sky_merge=true
